[package]
name = "kemuler"
version = "0.1.0"
edition = "2021"
description = "Experimental high level input simulation tool"
authors = [ "Multirious" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = { version = "0.1.1", optional = true }

[build-dependencies]
rustc_version = "0.4.0"

[features]
# Use Enigo as simulator
enigo = ["dep:enigo"]

# Use all features
all = ["enigo"]

[[example]]
name = "auto-clicker"
required-features = ["enigo"]

[[example]]
name = "mouse-circle"
required-features = ["enigo"]

[package.metadata.docs.rs]
all-features = true
