[package]
name = "kemuler"
version = "0.1.0"
authors = [ "Multirious" ]
edition = "2021"

description = "Experimental high level input simulation tool using combinators"
documentation = "https://docs.rs/kemuler"
homepage = "https://github.com/Multirious/kemuler"
repository = "https://github.com/Multirious/kemuler"
readme = "README.md"
keywords = ["input", "mouse", "testing", "keyboard", "automation"]
categories = ["development-tools::testing", "api-bindings", "hardware-support"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin_sleep = { version = "1.1.1", optional = true }

[dependencies.enigo]
version = "0.1.1"
optional = true 

[dependencies.windows]
version = "0.48.0"
features = [
  "Win32_UI_WindowsAndMessaging",
  "Win32_UI_Input",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_Foundation",
  "Win32_System_Threading",
]
optional = true 

[build-dependencies]
rustc_version = "0.4.0"

[features]
default = ["enigo", "windows"]

# more accurate thread sleep
spin_sleep = ["dep:spin_sleep"]

# Use Enigo as simulator
enigo = ["dep:enigo"]

# Window inputs simulator
# This has different implementation to Enigo.
windows = ["dep:windows"]

# this feature is currently a work around for https://github.com/rust-lang/rust/issues/67295
# uh do not use btw if you're not testing this crate's doctest.
# (it is not counted as a breaking change when removed)
test = []

[[example]]
name = "auto-clicker"
required-features = ["enigo"]

[[example]]
name = "mouse-circle"
required-features = ["enigo"]

[package.metadata.docs.rs]
features = ["enigo"]
