[package]
name = "kemuler"
version = "0.1.0"
edition = "2021"
description = "Experimental high level input simulation tool"
authors = [ "Multirious" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.0.12"

enigo = { version = "0.1.1", optional = true }

[features]
default = ["enigo"]
enigo = ["dep:enigo"]
