use crate::peripherals::{Keyboard, MouseButton};
use enigo::{
    Enigo, Key as EnigoKey, KeyboardControllable, MouseButton as EnigoMouseButton,
    MouseControllable,
};

use super::{KeyboardBackend, MouseBackend};

impl MouseBackend for Enigo {
    fn mouse_move_to(&self, x: i32, y: i32) {
        MouseControllable::mouse_move_to(&mut Enigo, x, y);
    }

    fn mouse_move_by(&self, x: i32, y: i32) {
        MouseControllable::mouse_move_relative(&mut Enigo, x, y);
    }

    fn mouse_scroll(&self, x: i32, y: i32) {
        MouseControllable::mouse_scroll_x(&mut Enigo, x);
        MouseControllable::mouse_scroll_y(&mut Enigo, y);
    }

    fn mouse_down(&self, button: &MouseButton) {
        MouseControllable::mouse_down(&mut Enigo, mouse_button_as_enigo(button));
    }

    fn mouse_up(&self, button: &MouseButton) {
        MouseControllable::mouse_up(&mut Enigo, mouse_button_as_enigo(button));
    }
}

impl KeyboardBackend for Enigo {
    fn key_down(&self, key: &Keyboard) {
        KeyboardControllable::key_down(&mut Enigo, keyboard_as_enigo(key));
    }

    fn key_up(&self, key: &Keyboard) {
        KeyboardControllable::key_up(&mut Enigo, keyboard_as_enigo(key));
    }
}

fn keyboard_as_enigo(keyboard: &Keyboard) -> EnigoKey {
    match keyboard {
        Keyboard::Num0 => EnigoKey::Num0,
        Keyboard::Num1 => EnigoKey::Num1,
        Keyboard::Num2 => EnigoKey::Num2,
        Keyboard::Num3 => EnigoKey::Num3,
        Keyboard::Num4 => EnigoKey::Num4,
        Keyboard::Num5 => EnigoKey::Num5,
        Keyboard::Num6 => EnigoKey::Num6,
        Keyboard::Num7 => EnigoKey::Num7,
        Keyboard::Num8 => EnigoKey::Num8,
        Keyboard::Num9 => EnigoKey::Num9,
        Keyboard::A => EnigoKey::A,
        Keyboard::B => EnigoKey::B,
        Keyboard::C => EnigoKey::C,
        Keyboard::D => EnigoKey::D,
        Keyboard::E => EnigoKey::E,
        Keyboard::F => EnigoKey::F,
        Keyboard::G => EnigoKey::G,
        Keyboard::H => EnigoKey::H,
        Keyboard::I => EnigoKey::I,
        Keyboard::J => EnigoKey::J,
        Keyboard::K => EnigoKey::K,
        Keyboard::L => EnigoKey::L,
        Keyboard::M => EnigoKey::M,
        Keyboard::N => EnigoKey::N,
        Keyboard::O => EnigoKey::O,
        Keyboard::P => EnigoKey::P,
        Keyboard::Q => EnigoKey::Q,
        Keyboard::R => EnigoKey::R,
        Keyboard::S => EnigoKey::S,
        Keyboard::T => EnigoKey::T,
        Keyboard::U => EnigoKey::U,
        Keyboard::V => EnigoKey::V,
        Keyboard::W => EnigoKey::W,
        Keyboard::X => EnigoKey::X,
        Keyboard::Y => EnigoKey::Y,
        Keyboard::Z => EnigoKey::Z,
        Keyboard::AbntC1 => EnigoKey::AbntC1,
        Keyboard::AbntC2 => EnigoKey::AbntC2,
        Keyboard::Accept => EnigoKey::Accept,
        Keyboard::Add => EnigoKey::Add,
        Keyboard::Alt => EnigoKey::Alt,
        Keyboard::Apps => EnigoKey::Apps,
        Keyboard::Attn => EnigoKey::Attn,
        Keyboard::Backspace => EnigoKey::Backspace,
        Keyboard::BrowserBack => EnigoKey::BrowserBack,
        Keyboard::BrowserFavorites => EnigoKey::BrowserFavorites,
        Keyboard::BrowserForward => EnigoKey::BrowserForward,
        Keyboard::BrowserHome => EnigoKey::BrowserHome,
        Keyboard::BrowserRefresh => EnigoKey::BrowserRefresh,
        Keyboard::BrowserSearch => EnigoKey::BrowserSearch,
        Keyboard::BrowserStop => EnigoKey::BrowserStop,
        Keyboard::Cancel => EnigoKey::Cancel,
        Keyboard::CapsLock => EnigoKey::CapsLock,
        Keyboard::Clear => EnigoKey::Clear,
        Keyboard::Control => EnigoKey::Control,
        Keyboard::Convert => EnigoKey::Convert,
        Keyboard::Crsel => EnigoKey::Crsel,
        Keyboard::DBEAlphanumeric => EnigoKey::DBEAlphanumeric,
        Keyboard::DBECodeinput => EnigoKey::DBECodeinput,
        Keyboard::DBEDetermineString => EnigoKey::DBEDetermineString,
        Keyboard::DBEEnterDLGConversionMode => EnigoKey::DBEEnterDLGConversionMode,
        Keyboard::DBEEnterIMEConfigMode => EnigoKey::DBEEnterIMEConfigMode,
        Keyboard::DBEEnterWordRegisterMode => EnigoKey::DBEEnterWordRegisterMode,
        Keyboard::DBEFlushString => EnigoKey::DBEFlushString,
        Keyboard::DBEHiragana => EnigoKey::DBEHiragana,
        Keyboard::DBEKatakana => EnigoKey::DBEKatakana,
        Keyboard::DBENoCodepoint => EnigoKey::DBENoCodepoint,
        Keyboard::DBENoRoman => EnigoKey::DBENoRoman,
        Keyboard::DBERoman => EnigoKey::DBERoman,
        Keyboard::DBESBCSChar => EnigoKey::DBESBCSChar,
        Keyboard::DBESChar => EnigoKey::DBESChar,
        Keyboard::Decimal => EnigoKey::Decimal,
        Keyboard::Delete => EnigoKey::Delete,
        Keyboard::Divide => EnigoKey::Divide,
        Keyboard::DownArrow => EnigoKey::DownArrow,
        Keyboard::End => EnigoKey::End,
        Keyboard::Ereof => EnigoKey::Ereof,
        Keyboard::Escape => EnigoKey::Escape,
        Keyboard::Execute => EnigoKey::Execute,
        Keyboard::Exsel => EnigoKey::Exsel,
        Keyboard::F1 => EnigoKey::F1,
        Keyboard::F2 => EnigoKey::F2,
        Keyboard::F3 => EnigoKey::F3,
        Keyboard::F4 => EnigoKey::F4,
        Keyboard::F5 => EnigoKey::F5,
        Keyboard::F6 => EnigoKey::F6,
        Keyboard::F7 => EnigoKey::F7,
        Keyboard::F8 => EnigoKey::F8,
        Keyboard::F9 => EnigoKey::F9,
        Keyboard::F10 => EnigoKey::F10,
        Keyboard::F11 => EnigoKey::F11,
        Keyboard::F12 => EnigoKey::F12,
        Keyboard::F13 => EnigoKey::F13,
        Keyboard::F14 => EnigoKey::F14,
        Keyboard::F15 => EnigoKey::F15,
        Keyboard::F16 => EnigoKey::F16,
        Keyboard::F17 => EnigoKey::F17,
        Keyboard::F18 => EnigoKey::F18,
        Keyboard::F19 => EnigoKey::F19,
        Keyboard::F20 => EnigoKey::F20,
        Keyboard::F21 => EnigoKey::F21,
        Keyboard::F22 => EnigoKey::F22,
        Keyboard::F23 => EnigoKey::F23,
        Keyboard::F24 => EnigoKey::F24,
        Keyboard::Final => EnigoKey::Final,
        Keyboard::GamepadA => EnigoKey::GamepadA,
        Keyboard::GamepadB => EnigoKey::GamepadB,
        Keyboard::GamepadDPadDown => EnigoKey::GamepadDPadDown,
        Keyboard::GamepadDPadLeft => EnigoKey::GamepadDPadLeft,
        Keyboard::GamepadDPadRight => EnigoKey::GamepadDPadRight,
        Keyboard::GamepadDPadUp => EnigoKey::GamepadDPadUp,
        Keyboard::GamepadLeftShoulder => EnigoKey::GamepadLeftShoulder,
        Keyboard::GamepadLeftThumbstickButton => EnigoKey::GamepadLeftThumbstickButton,
        Keyboard::GamepadLeftThumbstickDown => EnigoKey::GamepadLeftThumbstickDown,
        Keyboard::GamepadLeftThumbstickLeft => EnigoKey::GamepadLeftThumbstickLeft,
        Keyboard::GamepadLeftThumbstickRight => EnigoKey::GamepadLeftThumbstickRight,
        Keyboard::GamepadLeftThumbstickUp => EnigoKey::GamepadLeftThumbstickUp,
        Keyboard::GamepadLeftTrigger => EnigoKey::GamepadLeftTrigger,
        Keyboard::GamepadMenu => EnigoKey::GamepadMenu,
        Keyboard::GamepadRightShoulder => EnigoKey::GamepadRightShoulder,
        Keyboard::GamepadRightThumbstickButton => EnigoKey::GamepadRightThumbstickButton,
        Keyboard::GamepadRightThumbstickDown => EnigoKey::GamepadRightThumbstickDown,
        Keyboard::GamepadRightThumbstickLeft => EnigoKey::GamepadRightThumbstickLeft,
        Keyboard::GamepadRightThumbstickRight => EnigoKey::GamepadRightThumbstickRight,
        Keyboard::GamepadRightThumbstickUp => EnigoKey::GamepadRightThumbstickUp,
        Keyboard::GamepadRightTrigger => EnigoKey::GamepadRightTrigger,
        Keyboard::GamepadView => EnigoKey::GamepadView,
        Keyboard::GamepadX => EnigoKey::GamepadX,
        Keyboard::GamepadY => EnigoKey::GamepadY,
        Keyboard::Hangeul => EnigoKey::Hangeul,
        Keyboard::Hangul => EnigoKey::Hangul,
        Keyboard::Hanja => EnigoKey::Hanja,
        Keyboard::Help => EnigoKey::Help,
        Keyboard::Home => EnigoKey::Home,
        Keyboard::Ico00 => EnigoKey::Ico00,
        Keyboard::IcoClear => EnigoKey::IcoClear,
        Keyboard::IcoHelp => EnigoKey::IcoHelp,
        Keyboard::IMEOff => EnigoKey::IMEOff,
        Keyboard::IMEOn => EnigoKey::IMEOn,
        Keyboard::Insert => EnigoKey::Insert,
        Keyboard::Junja => EnigoKey::Junja,
        Keyboard::Kana => EnigoKey::Kana,
        Keyboard::Kanji => EnigoKey::Kanji,
        Keyboard::LaunchApp1 => EnigoKey::LaunchApp1,
        Keyboard::LaunchApp2 => EnigoKey::LaunchApp2,
        Keyboard::LaunchMail => EnigoKey::LaunchMail,
        Keyboard::LaunchMediaSelect => EnigoKey::LaunchMediaSelect,
        Keyboard::LButton => EnigoKey::LButton,
        Keyboard::LControl => EnigoKey::LControl,
        Keyboard::LeftArrow => EnigoKey::LeftArrow,
        Keyboard::LMenu => EnigoKey::LMenu,
        Keyboard::LShift => EnigoKey::LShift,
        Keyboard::LWin => EnigoKey::LWin,
        Keyboard::MButton => EnigoKey::MButton,
        Keyboard::MediaNextTrack => EnigoKey::MediaNextTrack,
        Keyboard::MediaPlayPause => EnigoKey::MediaPlayPause,
        Keyboard::MediaPrevTrack => EnigoKey::MediaPrevTrack,
        Keyboard::MediaStop => EnigoKey::MediaStop,
        Keyboard::Meta => EnigoKey::Meta,
        Keyboard::ModeChange => EnigoKey::ModeChange,
        Keyboard::Multiply => EnigoKey::Multiply,
        Keyboard::NavigationAccept => EnigoKey::NavigationAccept,
        Keyboard::NavigationCancel => EnigoKey::NavigationCancel,
        Keyboard::NavigationDown => EnigoKey::NavigationDown,
        Keyboard::NavigationLeft => EnigoKey::NavigationLeft,
        Keyboard::NavigationMenu => EnigoKey::NavigationMenu,
        Keyboard::NavigationRight => EnigoKey::NavigationRight,
        Keyboard::NavigationUp => EnigoKey::NavigationUp,
        Keyboard::NavigationView => EnigoKey::NavigationView,
        Keyboard::NoName => EnigoKey::NoName,
        Keyboard::NonConvert => EnigoKey::NonConvert,
        Keyboard::None => EnigoKey::None,
        Keyboard::Numlock => EnigoKey::Numlock,
        Keyboard::Numpad0 => EnigoKey::Numpad0,
        Keyboard::Numpad1 => EnigoKey::Numpad1,
        Keyboard::Numpad2 => EnigoKey::Numpad2,
        Keyboard::Numpad3 => EnigoKey::Numpad3,
        Keyboard::Numpad4 => EnigoKey::Numpad4,
        Keyboard::Numpad5 => EnigoKey::Numpad5,
        Keyboard::Numpad6 => EnigoKey::Numpad6,
        Keyboard::Numpad7 => EnigoKey::Numpad7,
        Keyboard::Numpad8 => EnigoKey::Numpad8,
        Keyboard::Numpad9 => EnigoKey::Numpad9,
        Keyboard::OEM1 => EnigoKey::OEM1,
        Keyboard::OEM102 => EnigoKey::OEM102,
        Keyboard::OEM2 => EnigoKey::OEM2,
        Keyboard::OEM3 => EnigoKey::OEM3,
        Keyboard::OEM4 => EnigoKey::OEM4,
        Keyboard::OEM5 => EnigoKey::OEM5,
        Keyboard::OEM6 => EnigoKey::OEM6,
        Keyboard::OEM7 => EnigoKey::OEM7,
        Keyboard::OEM8 => EnigoKey::OEM8,
        Keyboard::OEMAttn => EnigoKey::OEMAttn,
        Keyboard::OEMAuto => EnigoKey::OEMAuto,
        Keyboard::OEMAx => EnigoKey::OEMAx,
        Keyboard::OEMBacktab => EnigoKey::OEMBacktab,
        Keyboard::OEMClear => EnigoKey::OEMClear,
        Keyboard::OEMComma => EnigoKey::OEMComma,
        Keyboard::OEMCopy => EnigoKey::OEMCopy,
        Keyboard::OEMCusel => EnigoKey::OEMCusel,
        Keyboard::OEMEnlw => EnigoKey::OEMEnlw,
        Keyboard::OEMFinish => EnigoKey::OEMFinish,
        Keyboard::OEMFJJisho => EnigoKey::OEMFJJisho,
        Keyboard::OEMFJLoya => EnigoKey::OEMFJLoya,
        Keyboard::OEMFJMasshou => EnigoKey::OEMFJMasshou,
        Keyboard::OEMFJRoya => EnigoKey::OEMFJRoya,
        Keyboard::OEMFJTouroku => EnigoKey::OEMFJTouroku,
        Keyboard::OEMJump => EnigoKey::OEMJump,
        Keyboard::OEMMinus => EnigoKey::OEMMinus,
        Keyboard::OEMNECEqual => EnigoKey::OEMNECEqual,
        Keyboard::OEMPA1 => EnigoKey::OEMPA1,
        Keyboard::OEMPA2 => EnigoKey::OEMPA2,
        Keyboard::OEMPA3 => EnigoKey::OEMPA3,
        Keyboard::OEMPeriod => EnigoKey::OEMPeriod,
        Keyboard::OEMPlus => EnigoKey::OEMPlus,
        Keyboard::OEMReset => EnigoKey::OEMReset,
        Keyboard::OEMWsctrl => EnigoKey::OEMWsctrl,
        Keyboard::Option => EnigoKey::Option,
        Keyboard::PA1 => EnigoKey::PA1,
        Keyboard::Packet => EnigoKey::Packet,
        Keyboard::PageDown => EnigoKey::PageDown,
        Keyboard::PageUp => EnigoKey::PageUp,
        Keyboard::Pause => EnigoKey::Pause,
        Keyboard::Play => EnigoKey::Play,
        Keyboard::Print => EnigoKey::Print,
        Keyboard::Processkey => EnigoKey::Processkey,
        Keyboard::RButton => EnigoKey::RButton,
        Keyboard::RControl => EnigoKey::RControl,
        Keyboard::Return => EnigoKey::Return,
        Keyboard::RightArrow => EnigoKey::RightArrow,
        Keyboard::RMenu => EnigoKey::RMenu,
        Keyboard::RShift => EnigoKey::RShift,
        Keyboard::RWin => EnigoKey::RWin,
        Keyboard::Scroll => EnigoKey::Scroll,
        Keyboard::Select => EnigoKey::Select,
        Keyboard::Separator => EnigoKey::Separator,
        Keyboard::Shift => EnigoKey::Shift,
        Keyboard::Sleep => EnigoKey::Sleep,
        Keyboard::Snapshot => EnigoKey::Snapshot,
        Keyboard::Space => EnigoKey::Space,
        Keyboard::Subtract => EnigoKey::Subtract,
        Keyboard::Tab => EnigoKey::Tab,
        Keyboard::UpArrow => EnigoKey::UpArrow,
        Keyboard::VolumeDown => EnigoKey::VolumeDown,
        Keyboard::VolumeMute => EnigoKey::VolumeMute,
        Keyboard::VolumeUp => EnigoKey::VolumeUp,
        Keyboard::XButton1 => EnigoKey::XButton1,
        Keyboard::XButton2 => EnigoKey::XButton2,
        Keyboard::Zoom => EnigoKey::Zoom,
        Keyboard::Layout(char) => EnigoKey::Layout(*char),
        Keyboard::Raw(code) => EnigoKey::Raw(*code),
    }
}

fn mouse_button_as_enigo(mouse_button: &MouseButton) -> EnigoMouseButton {
    match mouse_button {
        MouseButton::Left => EnigoMouseButton::Left,
        MouseButton::Middle => EnigoMouseButton::Middle,
        MouseButton::Right => EnigoMouseButton::Right,
        MouseButton::Back => EnigoMouseButton::Back,
        MouseButton::Forward => EnigoMouseButton::Forward,
    }
}
